server:
  port: 7171
#  ssl:
#    enabled: true
#    key-store: file:/app/ssh/keystore.p12
#    key-store-password: 123452111
#    key-store-type: PKCS12
#    key-alias: myalias
#    key-password: 123452111

  servlet:
    context-path: /myapp
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8


  application:
    name: EmployeeService

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: postgresql

logging:
  level:
    org.springframework.web: DEBUG
    com.yourpackage: INFO
